services:
  postgres:
    container_name: postgres
    image: postgres:13.14-bullseye
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRESQL_USER}
      POSTGRES_PASSWORD: ${POSTGRESQL_PASSWORD}
      POSTGRES_DB: ${POSTGRESQL_DB}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    env_file:
      - .env
    networks:
      - assignment

networks:
  assignment:
    driver: bridge

volumes:
  postgres-data:
